//
//  LOVTypeEnum.swift
//  cafm
//
//  Created by NS on 21/09/24.
//  
//

import Foundation

enum LOVTypeEnum: String {
    case PROJECT_CONTRACT_SUB_CATEGORY = "PROJECT_CONTRACT_SUB_CATEGORY"
    case ASSET_SUB_CATEGORY_3 = "ASSET_SUB_CATEGORY_3"
    case SITE_CHECK_DOMESTIC_RA_SCORES = "SITE_CHECK_DOMESTIC_RA_SCORES"
    case AsbestosSurveyType2 = "Asbestos Survey (Type 2)"
    case ASBESTOS_PA_EXTENT_AMOUNT = "ASBESTOS_PA_EXTENT_AMOUNT"
    case ASBESTOS_PA_ACCESSIBILITY = "ASBESTOS_PA_ACCESSIBILITY"
    case ASBESTOS_MATERIAL_ASBESTOS_TYPE = "ASBESTOS_MATERIAL_ASBESTOS_TYPE"
    case ASSET_CATEGORY = "ASSET_CATEGORY"
    case SITE_CHECK_SURVEY_NORM_RUN_TIME = "SITE_CHECK_SURVEY_NORM_RUN_TIME"
    case ASBESTOS_PA_AVERAGE_USE = "ASBESTOS_PA_AVERAGE_USE"
    case SITE_CHECK_SURVEY_TEMPRATURE = "SITE_CHECK_SURVEY_TEMPRATURE"
    case ElectricalInstallationConditionReport = "Electrical Installation Condition Report"
    case ASBESTOS_PA_FREQUENCY_OF_USE = "ASBESTOS_PA_FREQUENCY_OF_USE"
    case ASBESTOS_MATERIAL_SURFACE = "ASBESTOS_MATERIAL_SURFACE"
    case STATUARY_CATEGORY = "STATUARY_CATEGORY"
    case ASSET_SUB_CATEGORY = "ASSET_SUB_CATEGORY"
    case SITE_CHECK_CATEGORY = "SITE_CHECK_CATEGORY"
    case ASBESTOS_PA_MAINTENANCE_ACTIVITY_TYPE = "ASBESTOS_PA_MAINTENANCE_ACTIVITY_TYPE"
    case ENERGY_COST_BUDGET_CATEGORY = "ENERGY_COST_BUDGET_CATEGORY"
    case SITE_CHECK_SURVEY_OUTLET_TYPE = "SITE_CHECK_SURVEY_OUTLET_TYPE"
    case ASBESTOS_PA_SECONDARY_ACTIVITY = "ASBESTOS_PA_SECONDARY_ACTIVITY"
    case ASSET_SUB_CATEGORY_2 = "ASSET_SUB_CATEGORY_2"
    case SITE_CHECK_SUB_TYPE = "SITE_CHECK_SUB_TYPE"
    case ASBESTOS_MATERIAL_ASSESSMENT_PRODUCT_TYPE = "ASBESTOS_MATERIAL_ASSESSMENT_PRODUCT_TYPE"
    case SITE_CHECK_TYPE = "SITE_CHECK_TYPE"
    case ASBESTOS_PA_LOCATION = "ASBESTOS_PA_LOCATION"
    case ASBESTOS_PA_MAINTENANCE_ACTIVITY_FREQ = "ASBESTOS_PA_MAINTENANCE_ACTIVITY_FREQ"
    case Gas = "Gas"
    case ASBESTOS_PA_MAIN_ACTIVITY = "ASBESTOS_PA_MAIN_ACTIVITY"
    case PROJECT_CONTRACT_CATEGORY = "PROJECT_CONTRACT_CATEGORY"
    case ASBESTOS_MATERIAL_DAMAGE = "ASBESTOS_MATERIAL_DAMAGE"
    case PASSIVE_FIRE_PROTECTION = "PASSIVE_FIRE_PROTECTION"
    case SITE_CHECK_AUDIT_HEADER = "SITE_CHECK_AUDIT_HEADER"
}
